name: Update Portal

on:
  push:
    branches: 
      - master
      
  workflow_dispatch:

jobs:
  update-portal:
    runs-on: ubuntu-latest
    
    env: 
      API_ENTITY_ID: 61c08865a54579a7191c5c69 
    steps:
    
    - name : checkout-repo
      uses: actions/checkout@v2
      with:
          ref: 'master'
      id: checkout-repo 
     

    - name: Install zip action
      uses: montudor/action-zip@v0.1.1    
      
    - name: install zip 
      run: sudo apt-get install zip unzip
      
    - name: zip files
      run: zip -r portal-input.zip *
      working-directory: spec

    - name: list
      run: zip -sf portal-input.zip
      working-directory: spec

    - name: inplace-import
      #run: curl -X PUT --url 'https://www.apimatic.io/api/api-entities/${{ env.API_ENTITY_ID }}' -H 'content-type:multipart/form-data' -H 'Authorization:${{ secrets.CREDENTIALS }}' -F 'file=@spec/portal-input.zip'
      run: curl -X PUT --url 'https://www.apimatic.io/api/api-entities/${{ secrets.API_ENTITY_ID }}' -H 'content-type:multipart/form-data' -H 'Authorization:X-Auth-Key ${{ secrets.API_KEY }}' -F 'file=@spec/portal-input.zip'

      #run: curl -X PUT --url 'https://apimaticio-test.azurewebsites.net/api/api-entities/${{ env.API_ENTITY_ID }}/import-via-file' -H 'Authorization:${{ secrets.CREDENTIALS }}' -H 'Accept:application/vnd.apimatic.apiEntity.full.v1+json' -F 'file=@spec/portal-input.zip'

#     - name: publish-hosted-portal
#       run: curl --location --request PUT 'https://www.apimatic.io/api/api-entities/${{ env.API_ENTITY_ID }}/portal/publish' -H 'Content-Length:0' -H 'Authorization:${{ secrets.CREDENTIALS }}'

    - name: publish-portal
      run: curl --location --request PUT 'https://www.apimatic.io/api/api-entities/${{ secrets.API_ENTITY_ID }}/portal/publish' -H 'Content-Length:0' -H 'Authorization:X-Auth-Key ${{ secrets.API_KEY }}'
