name: Update Portal

on:
  workflow_dispatch:  
  push:
    branches: 
      - master 
    paths:
      - 'spec/**'  

jobs:
  update-portal:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v1
      name : checkout-repo
      id: checkout-repo   
      
#     - name: import
#       run: curl -X POST --url 'https://apimaticio-test.azurewebsites.net/api/api-entities/import-via-file' -H 'Authorization:X-Auth-Key ${{ secrets.API_KEY }}' -H 'Accept:application/json' -H 'Content-Type:multipart/form-data' -F 'file=@spec/APIMATIC Calculator-OpenApi3Json.json'
     
    - name: inplace-import
      run: curl -X PUT --url 'https://www.apimatic.io/api/api-entities/${{ secrets.API_ENTITY_ID }}' -H 'content-type:multipart/form-data' -H 'Authorization:X-Auth-Key ${{ secrets.API_KEY }}' -F 'file=@spec/MMjson.json'
      
# Uncomment the following step to publish your Portal. The portal must first be published manually for this step to work successfully.
#     - name: publish-portal
#       run: curl --location --request PUT 'https://www.apimatic.io/api/api-entities/${{ secrets.API_ENTITY_ID }}/portal/publish' -H 'Content-Length:0' -H 'Authorization:X-Auth-Key ${{ secrets.API_KEY }}'
